### ISSUE TITLE
BUILD FAILED UE4

### ISSUE THREAD

**Issue by slavazx** [botman99/ue4-unreal-automation-tool#1]
Running AutomationTool...
Parsing command line: -ScriptsForProject=G:/Throughthecenturies/Throughthecenturies.uproject BuildCookRun -project=G:/Throughthecenturies/Throughthecenturies.uproject -noP4 -clientconfig=Development -serverconfig=Development -nocompile -nocompileeditor -installed -ue4exe=F:\UE_4.27\Engine\Binaries\Win64\UE4Editor-Cmd.exe -utf8output -platform=Win64 -targetplatform=Win64 -ini:Game:[/Script/UnrealEd.ProjectPackagingSettings]:BlueprintNativizationMethod=Disabled -build -cookonthefly -map= -compressed -stage -deploy -cmdline=" -Messaging" -device=WindowsNoEditor@DESKTOP-GS70S26 -addcmdline="-SessionId=28EDABD042DAD1C914DCC9A1BC67F826 -SessionOwner='slava' -SessionName='DESKTOP-GS70S26'  " -run
Setting up ProjectParams for G:\Throughthecenturies\Throughthecenturies.uproject
Throughthecenturies.uproject requires a temporary target.cs to be generated (AchievementSystem plugin is enabled)
While compiling C:\Users\slava\AppData\Local\Temp\UAT\F+UE_4.27\Rules\UATRules-1403487690.dll:
g:\Throughthecenturies\Intermediate\Source\Through the centuries.Target.cs(3,22) : error CS1514: ????????? {
g:\Throughthecenturies\Intermediate\Source\Through the centuries.Target.cs(3,42) : error CS1002: ????????? ;
g:\Throughthecenturies\Intermediate\Source\Through the centuries.Target.cs(4,1) : error CS1519: ???????????? ????? "{" ? ?????????? ??????, ????????? ??? ??????????
g:\Throughthecenturies\Intermediate\Source\Through the centuries.Target.cs(5,21) : error CS1002: ????????? ;
g:\Throughthecenturies\Intermediate\Source\Through the centuries.Target.cs(5,56) : error CS1002: ????????? ;
g:\Throughthecenturies\Intermediate\Source\Through the centuries.Target.cs(5,69) : error CS1519: ???????????? ????? ")" ? ?????????? ??????, ????????? ??? ??????????
g:\Throughthecenturies\Intermediate\Source\Through the centuries.Target.cs(7,8) : error CS1519: ???????????? ????? "=" ? ?????????? ??????, ????????? ??? ??????????
g:\Throughthecenturies\Intermediate\Source\Through the centuries.Target.cs(7,25) : error CS1519: ???????????? ????? ";" ? ?????????? ??????, ????????? ??? ??????????
g:\Throughthecenturies\Intermediate\Source\Through the centuries.Target.cs(8,23) : error CS1519: ???????????? ????? "(" ? ?????????? ??????, ????????? ??? ??????????
g:\Throughthecenturies\Intermediate\Source\Through the centuries.Target.cs(10,1) : error CS1022: ????????? ??????????? ???? ??? ???????????? ????, ???? ??????? ????? ?????
ERROR: Unable to compile source files.
       (see C:\Users\slava\AppData\Roaming\Unreal Engine\AutomationTool\Logs\F+UE_4.27\Log.txt for full exception trace)
AutomationTool exiting with ExitCode=1 (Error_Unknown)
BUILD FAILED

Through the centuries name of the game

**Comment by botman99** [comment]
Are the spaces in "Through the centuries.Target.cs"?  Don't use spaces in the file names.  Attach your 'Through the centuries.Target.cs' file.

**Comment by slavazx** [comment]
Thank you very much
