### ISSUE TITLE
Packaging failed UE4 Help please

### ISSUE THREAD

**Issue by slavazx** [botman99/ue4-unreal-automation-tool#3]
ATHelper: Packaging (Windows (64-bit)):   LogInit: Display: NOTE: Only first 50 warnings displayed.
UATHelper: Packaging (Windows (64-bit)):   LogInit: Display:
UATHelper: Packaging (Windows (64-bit)):   LogInit: Display: Failure - 1 error(s), 302 warning(s)
UATHelper: Packaging (Windows (64-bit)):   LogInit: Display:
UATHelper: Packaging (Windows (64-bit)):   
UATHelper: Packaging (Windows (64-bit)):   Execution of commandlet took:  1144.69 seconds
UATHelper: Packaging (Windows (64-bit)):   LogShaderCompilers: Display: === FShaderJobCache stats ===
UATHelper: Packaging (Windows (64-bit)):   LogShaderCompilers: Display: Total job queries 0, among them cache hits 0 (0.00%)
UATHelper: Packaging (Windows (64-bit)):   LogShaderCompilers: Display: Tracking 0 distinct input hashes that result in 0 distinct outputs (0.00%)
UATHelper: Packaging (Windows (64-bit)):   LogShaderCompilers: Display: RAM used: 0.00 MB (0.00 GB) of 409.60 MB (0.40 GB) budget. Usage: 0.00%
UATHelper: Packaging (Windows (64-bit)):   LogShaderCompilers: Display: 

UATHelper: Packaging (Windows (64-bit)):   LogHttp: Display: cleaning up 0 outstanding Http requests.
UATHelper: Packaging (Windows (64-bit)):   LogContentStreaming: Display: There are 1 unreleased StreamingManagers
UATHelper: Packaging (Windows (64-bit)): Took 1277,9703187s to run UE4Editor-Cmd.exe, ExitCode=1
UATHelper: Packaging (Windows (64-bit)): ERROR: Cook failed.
UATHelper: Packaging (Windows (64-bit)):        (see C:\Users\slava\AppData\Roaming\Unreal Engine\AutomationTool\Logs\F+UE_4.27\Log.txt for full exception trace)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=25 (Error_UnknownCookFailure)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Cook Failure

**Comment by botman99** [comment]
"C:\Users\slava\AppData\Roaming\Unreal Engine\AutomationTool\Logs\F+UE_4.27\Log.txt"

I'm not sure why there's "F+UE_4.27" in there.  Is your project in a folder named "F+UE_4.27" or something?  Project names should contain no spaces or other special characters (like '+').

**Comment by slavazx** [comment]
How to fix it?

**Comment by botman99** [comment]
Try renaming your project to something simple, like "MyProject".

**Comment by slavazx** [comment]
Sorry, this is my first time doing this.
Another mistake  
UATHelper: Packaging (Windows (64-bit)): WARNING: Error while enumerating Visual Studio toolchains
UATHelper: Packaging (Windows (64-bit)): WARNING: Assuming no compilation capability.
PackagingResults: Warning: Error while enumerating Visual Studio toolchains
PackagingResults: Warning: Assuming no compilation capability.
UATHelper: Packaging (Windows (64-bit)): Setting up ProjectParams for P:\Throughthecenturies\MyProjec.uproject
UATHelper: Packaging (Windows (64-bit)): MyProjec.uproject requires a temporary target.cs to be generated (ApexDestruction plugin is enabled)
UATHelper: Packaging (Windows (64-bit)): ERROR: P:\Throughthecenturies\MyProjec.uproject does not look like uproject file but no targets have been found!
UATHelper: Packaging (Windows (64-bit)):        (see C:\Users\slava\AppData\Roaming\Unreal Engine\AutomationTool\Logs\A+UE_4.27\Log.txt for full exception trace)
PackagingResults: Error: P:\Throughthecenturies\MyProjec.uproject does not look like uproject file but no targets have been found!
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=1 (Error_Unknown)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Error
