### ISSUE TITLE
Is there a way to package "WindowsYesEditor"?

### ISSUE THREAD

**Issue by iMaciaP** [botman99/ue4-unreal-automation-tool#4]
HI,

First of all very nice info and well explained. Nice work!

My question is, is there a way to include editor in the buid? I can achieve a reduced version of unreal engine?

For example, educatinoal purposes, only left the place actors and some simple modules and the resoult and .exe with editor itself reduced. That's why im refereanig to folder as "WindowsYesEditor", or maybe the builds are always targeted to a project? My project in this case would be editor itself.

Thank you!!

**Comment by botman99** [comment]
You can not redistribute the editor (per the EULA).  See this thread:

https://forums.unrealengine.com/t/ue4-is-free-can-we-package-the-editor/308753

**Comment by iMaciaP** [comment]
Ok im not about to redistribute the editor, but i want to achive something like "modding kit" listed in epic games store. Do you know any place to start looking for info?

Examples:

VRFunhouse, unreal tournament editor, ark modkit.... etc

listed in

Epic games store > browse > types > editor

**Comment by botman99** [comment]
No, I don't know.  You should ask for the process on Epic's forums.
